import VerticalNavbar from "../components/VerticalNavbar";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import NftCard from "../components/NftCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <div className={styles.mainContainer}>
          <div className={styles.mainWrapper}>
            <VerticalNavbar />
            <div className={styles.mainWrapperInner}>
              <NftCard />
              <NftCard />
              <NftCard />
              <NftCard />
              <NftCard />
              <NftCard />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
